### ISSUE TITLE
request : last highscore

### ISSUE THREAD

**Issue by yeKcim** [vicgeralds/vitetris#12]
highlight last high score

**Comment by laautarolopez** [comment]
I want to take this issue. How can I communicate with the owner?

**Comment by laautarolopez** [comment]
I am working for a project at my university, I need help

**Comment by vicgeralds** [comment]
I am right here if you want to discuss the issue.

**Comment by laautarolopez** [comment]
I am on linux, I cloned the repository on pc, and I cannot create the directory of the tetris file.
I made changes but I can't test them

**Comment by vicgeralds** [comment]
I thought you offered to help solving this issue. You need help?

**Comment by laautarolopez** [comment]
Obviously, I want to solve the problem. But I don't want to pull request before testing. So i want to create the file of the tetris for testing.

**Comment by vicgeralds** [comment]
You should be able to do that. I’m not sure I can help a lot with testing, that’s really most of the job.

**Comment by laautarolopez** [comment]
I am seeing that the vitetris-hiscores file when executing is not created. 
I think it should be added directly to the repository. Is it in .cfg format?

**Comment by vicgeralds** [comment]
Running make install will tell you how to create the system-wide highscore file if wanted. I made it an option to use it.

You can figure out answers like these yourself. As a student you have way more time than me to figure out how things work than me (but I don’t really recommend that you invest a lot of time in this codebase). I don’t understand code I wrote more than 10 years ago very well.

**Comment by laautarolopez** [comment]
Is vitetris-hiscores file in .cfg format? I need to know that so i can attach it to repository.

**Comment by vicgeralds** [comment]
I don’t know what you mean by .cfg format. It’s some kind of INI file. Or binary possibly, since I didn’t use utf-8 back then :D

**Comment by laautarolopez** [comment]
Because when I downloaded the game on windows the high scores were saved in vitetris.cfg.
I saw that when I run ./tetris.exe -help.

**Comment by laautarolopez** [comment]
Do you think adding the system-wide highscore file to the repository? Thus, later problems are avoided when creating it.
The user could move the file in the path he wants.

PD: The client must inform the path of the file.

**Comment by vicgeralds** [comment]
Please stop discussing the system-wide highscore file here. I don’t see how it’s related to the feature request to highlight the last high score.
