### ISSUE TITLE
XDG Base Directory support

### ISSUE THREAD

**Issue by soredake** [vicgeralds/vitetris#19]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Store `~/.vitetris` in `$XDG_DATA_HOME/vitetris`

**Comment by soredake** [comment]
@vicgeralds

**Comment by port19x** [comment]
Yes, storing stuff in your home directory like this without a really good reason to do so is bad practice and easily fixable.

**Comment by vicgeralds** [comment]
I don't know, storing stuff in your home directory like this is stilll common practice. This game/project was all about doing things for no good reason anyway. I have no plans to fix all the things myself that someone may label as bad practice. Programming in C is bad practice these days if you ask some.

Anyway, storing config in `$XDG_DATA_HOME/vitetris` (that is, `~/.local/share/vitetris`) seem wrong too me. There's also `$XDG_CONFIG_HOME` (`~/.config` if unset), but writing high scores (encoded as binary bytes!) to a config file there seems even more wrong. So maybe not so easily fixable.
