### ISSUE TITLE
Thanks for your work!

### ISSUE THREAD

**Issue by ryzhovau** [vicgeralds/vitetris#2]
I want to thank you for `vitetris`, which was ported to [Entware](https://github.com/Entware/Entware) repo five years ago. Here is an asciicast of playing `vitetris` between me and @zyxmon on MIPS-based home routers.

[![asciicast](https://asciinema.org/a/6733.png)](https://asciinema.org/a/6733)

Thanks again!

**Comment by vicgeralds** [comment]
Good to hear!
