### ISSUE TITLE
Since 0.59.0, the "brackets" block style does not save

### ISSUE THREAD

**Issue by augmentedfourth** [vicgeralds/vitetris#20]
I prefer the `[brackets] []` block style, but since 0.59.0, that choice is not remembered across plays. The block style now returns to `[default ] #` when I quit and restart the game.

**Comment by vicgeralds** [comment]
Thanks for reporting. I think I know how to fix it.

**Comment by augmentedfourth** [comment]
That fixed it! Thanks!

I'm also submitting a Homebrew pull request so that I can install from the master branch rather than a release tarball: https://github.com/Homebrew/homebrew-core/pull/67600
