### ISSUE TITLE
Premature "GAME OVER"

### ISSUE THREAD

**Issue by keeganjk** [vicgeralds/vitetris#22]
Sometimes I experience a "Game Over" before reaching the top of the game-playing area. It seems to happen whenever clearing a row/several rows.

**Comment by keeganjk** [comment]
It seems like it might be happening whenever a way back to the bottom level is re-opened after being covered.

![2021-06-29_11-30-05](https://user-images.githubusercontent.com/24554125/123826095-75babe00-d8cd-11eb-8a85-cd4ca6ce9522.png)

**Comment by vicgeralds** [comment]
I think you have selected game mode B-type and have cleared all the lines. So game over here means you completed the game successfully (not obvious, I know).

Duplicate of #10

**Comment by keeganjk** [comment]
Yes, that was the problem, thank you. The difference between the modes is not at all obvious, maybe it could be (more clearly) documented or added directly into the game.
