### ISSUE TITLE
「./tetris: Shared object "libX11.so.7" not found」 error in NetBSD 8.0.

### ISSUE THREAD

**Issue by kapper1224** [vicgeralds/vitetris#5]
I build vitetris in NetBSD 8.0 amd64.
「./tetris: Shared object "libX11.so.7" not found」 error in it.
I test copy library,

cp /usr/X11R7/lib/libX11.so.7 /usr/lib/

After I can play vitetris in NetBSD.
Please add library path in  vitetris.

Thank you.

**Comment by vicgeralds** [comment]
Yes, seems like /usr/X11R7/lib needs to be added to the runtime library search path in NetBSD. That can be done by adding the option `-Wl,-R/usr/X11R7/lib` when linking. So the configure script should add that option to LDFLAGS in config.mk.

(found similar issue: https://stackoverflow.com/questions/21288007/netbsd-dynamic-lib-error-after-compiling-cwm#21292340)

**Comment by kapper1224** [comment]
Thank you very much!
I rebuild and test it now.
Fixed it in my NetBSD 8.0.
